# Generated by Django 5.0.3 on 2024-03-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('medical_condition', models.CharField(max_length=255)),
                ('side_effects', models.TextField()),
                ('generic_name', models.CharField(max_length=255)),
                ('drug_classes', models.CharField(max_length=255)),
                ('brand_names', models.CharField(max_length=4000)),
                ('activity', models.CharField(max_length=255)),
                ('rx_otc', models.CharField(max_length=10)),
                ('pregnancy_category', models.CharField(max_length=1)),
                ('csa', models.CharField(max_length=1)),
                ('alcohol', models.CharField(max_length=1)),
                ('related_drugs', models.TextField()),
                ('medical_condition_description', models.TextField()),
                ('rating', models.FloatField()),
                ('no_of_reviews', models.IntegerField()),
                ('drug_link', models.URLField()),
                ('medical_condition_url', models.URLField()),
            ],
            options={
                'db_table': 'Drugs',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('formula', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('drug_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_drug_1', to='interactions.drug')),
                ('drug_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_drug_2', to='interactions.drug')),
            ],
        ),
    ]
