# Generated by Django 5.0.3 on 2024-03-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rule',
            table='drug_interaction_rules',
        ),
    ]
