# Generated by Django 5.0.3 on 2024-03-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_remove_rule_id_rule_rule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='formula',
            new_name='expression',
        ),
    ]
