# Generated by Django 5.0.3 on 2024-03-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_rename_formula_rule_expression'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='expression',
            new_name='formula',
        ),
    ]
