# Generated by Django 5.0.3 on 2024-04-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_rename_expression_rule_formula'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table='Drugs_bayesian',
        ),
    ]
