# Generated by Django 5.0.3 on 2024-04-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_alter_drug_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table='Drugs',
        ),
    ]
