# Generated by Django 5.0.3 on 2024-04-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_alter_drug_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rule',
            table=None,
        ),
    ]
