# Generated by Django 5.0.3 on 2024-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_alter_drug_table_alter_rule_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
