# Generated by Django 5.0.3 on 2024-04-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BayesianNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('medical_condition', models.CharField(max_length=255)),
                ('side_effects', models.TextField()),
                ('generic_name', models.CharField(max_length=255)),
                ('drug_classes', models.CharField(max_length=255)),
                ('brand_names', models.CharField(max_length=4000)),
                ('activity', models.CharField(max_length=255)),
                ('rx_otc', models.CharField(max_length=10)),
                ('pregnancy_category', models.CharField(max_length=1)),
                ('csa', models.CharField(max_length=1)),
                ('alcohol', models.CharField(max_length=1)),
                ('related_drugs', models.TextField()),
                ('medical_condition_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BayesianEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_edges', to='bayesian.bayesiannode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_edges', to='bayesian.bayesiannode')),
            ],
        ),
    ]
