# Generated by Django 5.0.3 on 2024-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayesian', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug',
            new_name='Drug_bayesian',
        ),
    ]
