# Generated by Django 5.0.3 on 2024-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayesian', '0003_alter_drug_bayesian_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drug_bayesian',
            table=None,
        ),
    ]
